### ISSUE TITLE
Filtering to a subset of users

### ISSUE THREAD

**Issue by dhardiker** [mrkno/PlexSSOv2#3]
Hi,

I've got this working where authentication works via Plex - however it seems to allow anyone who has a Plex login (i.e. you can just sign up to Plex and get into my system if you know the URL). I would like it to be restricted to only specific users.

Is that possible, either through nginx or PlexSSOv2 configuration?

**Comment by mrkno** [comment]
Right now if you can get into the Plex server you this will allow you through.

I want to add further controls on top of that, and it should be fairly simple to do I just have not had time.

**Comment by mrkno** [comment]
This is now possible using the configuration file.
